quarkus:
  http:
    cors: true
  log:
    category:
      "io.quarkus.category":
        level: INFO
  swagger-ui:
    always-include: true
  native:
    container-build: true
mp:
  openapi:
    filter: ru.faulab.cloud.bookstore.application.OpenApiEnricher
"%dev":
  mp:
    openapi:
      servers: "http://localhost:8080,http://127.0.0.1:8080"