# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "daily"
