apiVersion: v1
kind: Service
metadata:
  name: bookshop
  labels:
    app: bookshop
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: bookshop
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop
spec:
  selector:
    matchLabels:
      app: bookshop
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: bookshop
        tier: frontend
    spec:
      containers:
        - name: bookshop-frontend
          image: k8s.gcr.io/redis:e2e  # or just image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: TEMP
              value: env
          ports:
            - containerPort: 80