name: Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14.0
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 14.0
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B clean package -Pnative --file backend/pom.xml
      - name: Build the Docker image
        run: docker build -f backend/bookstore/application/src/main/docker/Dockerfile.native -t cloud-native/bookstore backend/bookstore/application